#%RAML 1.0
# esto es un comentario
title: "Mi primera API"
version: 1.0
baseUri: "https://miprimeraapi.com/{version}"
protocols: [HTTP, https]
documentation: 
  - title: "Títlo relacionado con la documentación del usuario"
  - content: |
        va a ocupar 
        más de una línea

# definición de recursos
/helloWorld