#%RAML 1.0 ResourceType
  usage: Tipo de recurso para trabajar con colecciones
  description: Una coleccion de <<resourcePathName>>
  get:
      description: Recuperar todas las <<resourcePathName>> de forma paginada
      queryParameters: 
      offset:
          displayName: Offset
          type: integer
          description: Número de página a la que vamos a acceder
          required: true
      size:
          displayName: Tamaño de la página
          type: integer
          description: Tamaño de la página que se recupera
          required: true
      responses: 
          200:
          body: 
              type: <<tipoEntidad>> []  
  post:
      description: Crear <<tipoEntidad>>
      body: 
      application/json:
      type: <<tipoEntidad>>
      responses:
      201: 
          body: 
          type: <<tipoEntidad>>
      404:
          description: El recurso no ha sido encontrado
          body: 
          type: Mensaje