#%RAML 1.0
--- 
title: "API para la gestión de documentos de la organización"
version: 1.0
baseUri: "https://empresa.com/{version}"
protocols: [HTTPS]
documentation: 
  - title: "API para la gestión de documentos de la organización"
mediaType: application/json
types: !include types/documentos.raml
resourceTypes: 
  coleccion: !include resource-types/coleccion.raml
/facturas:
  type: {coleccion:{"tipoEntidad": "Factura"}}
  put:
    description: Actualizar factura
    body: 
    responses: 
      200:
        description: La operación se ha realizado con éxito
        body: 
          application/json:
          type: Mensaje
      404: 
        description: El recurso no ha sido encontrado
  /{facturaId}: 
    get:
      description: Recuperar factura por id
      responses: 
        200:
          description: La operación se ha realizado con éxito
          body: 
            application/json:
            type: Factura         
        404:
          description: El recurso no ha sido encontrado
    delete:
      description: Borrar factura por id
      responses: 
        200: 
        404: 
          description: El recurso no ha sido encontrado

/albaranes:
  type: {coleccion:{"tipoEntidad": "Albaran"}} 